% Sun 11 Mar 20:40:28 CET 2018
%% plot result
function obj = plot(obj,Xi,Q0,W0,S0,z1_downstream,cd,zb_downstream,omega,q,opt)
	Xi  = Xi{1};
	L   = Xi(2)-Xi(1);
	key = obj.key(...	
			opt.model_str, ...
			func2str(opt.solver), ...
			zb_downstream, ...
			S0, ...
			W0, ...
			cd, ...
			Q0, ...
			z1_downstream, ...
			omega,   ...
			q, ...
			L,	 ...
			opt.nx,	 ...
			opt.xs ...
		);
	if (isKey(obj.rt,key))
		out = obj.rt(key);
		x = out.x;
		z = [out.zb, out.z0];
		figure();
		plot(x,z,'linewidth',2);
		hold on
		plot(x, out.initial.z0,'.-');
		title(sprintf('Q0 %g z1 %g S0 %g',Q0,z1_downstream,S0));
	else
		error('key does not exist');
	end
end

