% Sun  8 Oct 13:08:39 CEST 2017
% Karl Kastner, Berlin
%
function f = odefun_ghof(obj,k,q0,qhr,h0,dz0_dx,cD,c0,c1,c2,Pi)
	o1     = obj.omega;
	g      = obj.g;
	flag   = obj.flag;
	f      = zeros(size(q0,1),4);
	if (obj.issym)
		f = sym(f);
	end
	switch (k)
	case {1}
		f(:,2) = ( ...
		   flag.gh*(1i*g*dz0_dx)./(h0*k*o1) ...
		 + flag.oh*( (3i*c2.*cD.*q0.^2) ...
			    +(3i*cD.*q0.*c1.*qhr) ...
			    +(3i*cD.*c0.*qhr.^2))./(h0.^4*k*o1*Pi) ...
		 + flag.oh*flag.gh*(+( (3*1i*c0.*cD.*qhr.^2)...
			              +(3i*c1.*cD.*q0.*qhr) ...
                                      +(3i*c2.*cD.*q0.^2))./(h0.^3*o1*Pi) ...
                                    -( (2i*c0.*cD.*qhr.^2) ...
				      +(2i*c1.*cD.*q0.*qhr) ...
                                      +(2i*c2.*cD.*q0.^2) )./(h0.^4*o1*Pi)) ...
		  );
	end
end

