% Wed 11 Oct 10:18:54 CEST 2017
%% solve for the oscillatory (tidal) componets
%%
%% function obj   = solve_wave(obj)
function [y, obj]   = solve_wave(obj)

	% solve the system of ode's
	opt = obj.opt;

	obj.out = feval( obj.opt.solver  ...
			                , {@obj.odefun} ...
			                , {@obj.bcfun} ...
					, {@opt.ifun} ... %{@obj.opt.ifun} ...
				        , obj.Xi ...
					, obj.opt.nx ...
					, {} ...
					, obj.opt.dischargeisvariable ...
				        , obj.opt ...
		       );

	obj.postprocess(obj.out.x,obj.out.y,obj.out.yc);

	y = obj.out.y;
end % River_Tide/solve_wave

